### ISSUE TITLE
Trouble after update to 0.15.0

### ISSUE THREAD

**Issue by nicolas-j** [sailoog/openplotter#181]
Openplotter would not start:

Traceback (most recent call last):
  File "/home/pi/.config/openplotter/openplotter", line 3488, in <module>
    MainFrame().Show()
  File "/home/pi/.config/openplotter/openplotter", line 250, in __init__
    self.read_i2c()
  File "/home/pi/.config/openplotter/openplotter", line 1859, in read_i2c
    self.list_i2c.Append([str(c), name, address, magn_list[c], iii[0], str(iii[1]), str(iii[2])])
UnboundLocalError: local variable 'magn_list' referenced before assignment

**Comment by sailoog** [comment]
http://forum.openmarine.net/showthread.php?tid=660&pid=2501#pid2501
