### ISSUE TITLE
update to signalk 1.1.1

### ISSUE THREAD

**Issue by Dirk--** [sailoog/openplotter#199]
manual update to signalk-server-node 1.1.1 seems to be working (nodejs 8.x needed):

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install nodejs
cd /home/pi/.config
rm -rf signalk-server-node_tmp
git clone https://github.com/SignalK/signalk-server-node.git signalk-server-node_tmp
cd signalk-server-node_tmp
npm install && npm run prepublishOnly
npm install mdns
cd /home/pi/.config
rm -rf signalk-server-node
mv signalk-server-node_tmp signalk-server-node

please note 'Develop: Install from git' at https://github.com/SignalK/signalk-server-node/blob/master/README.md

**Comment by sailoog** [comment]
Yes, we know. OpenPlotter update process uses a signalk-server-node fork previous to that change. Current OP version will no be updated any longer. We are working on the new release with debian stretch, Raspberry 3B+ compatible, moitessier hat support, pypilot, and better signal k integration from npm package.

**Comment by CaptainRon47** [comment]
I tried following the above procedure to upgrade the Signalk-server on an Rpi running OpenPLotter.  I got to this statement npm install && npm run prepublishOnly  and it ended by dumping a log file that has these errors as the last lines    error code EINTEGRITY   error sha512-.....   integrity checksum failed  
Any thoughts on this?

**Comment by CaptainRon47** [comment]
I tried, from the beginning, a second time and got the same result.
When I go thru the build it indicates (in the /.npm/_logs/XXXX-debug.log file that it is building SKserver1.1.2?   It exits with an error, here are the last few lines of the log file:
11500 verbose stack Error: sha512-bqB1yS6o9TNA9ZC/MJxM0FZzPnZdtHj0xWK/IZ5khzVqdpGul/R/EIiHRgFXlwTD7PSIaYVnGKq1QgMCu2mnqw== integrity checksum failed when using sha512: wanted sha512-bqB1yS6o9TNA9ZC/MJxM0FZzPnZdtHj0xWK/IZ5khzVqdpGul/R/EIiHRgFXlwTD7PSIaYVnGKq1QgMCu2mnqw== but got sha512-+V8TBETXXoP1uK4Bs2J+CaOL7xmhQGGT/AVDzyDEJdvzwQWRY66u9YBf9iMdPolp6yScIiT2+AS6GsvMubOsww==. (1818624 bytes)
11500 verbose stack     at Transform.on (/usr/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
11500 verbose stack     at emitNone (events.js:111:20)
11500 verbose stack     at Transform.emit (events.js:208:7)
11500 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
11500 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11500 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
11501 verbose cwd /home/pi/.config/signalk-server-node_tmp
11502 verbose Linux 4.9.35-v7+
11503 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
11504 verbose node v8.11.1
11505 verbose npm  v5.6.0
11506 error code EINTEGRITY
11507 error sha512-bqB1yS6o9TNA9ZC/MJxM0FZzPnZdtHj0xWK/IZ5khzVqdpGul/R/EIiHRgFXlwTD7PSIaYVnGKq1QgMCu2mnqw== integrity checksum failed when using sha512: wanted sha512-bqB1yS6o9TNA9ZC/MJxM0FZzPnZdtHj0xWK/IZ5khzVqdpGul/R/EIiHRgFXlwTD7PSIaYVnGKq1QgMCu2mnqw== but got sha512-+V8TBETXXoP1uK4Bs2J+CaOL7xmhQGGT/AVDzyDEJdvzwQWRY66u9YBf9iMdPolp6yScIiT2+AS6GsvMubOsww==. (1818624 bytes)
11508 verbose exit [ 1, true ]

**Comment by CaptainRon47** [comment]
Well, I think I got it.  What I did this time was to first upgrade to OpenPlotter  0.17.1 stable.  Then follow the above procedures, but before the npm install I ran   "npm config set package-lock false"  this time the install completed ok.  After a reboot and running OPenPlotter I can go to Chrome and open the SignalK server GUI version 1.1.2!

**Comment by CaptainRon47** [comment]
In SKServer ver 1.1.2 when you update informaton (vessel data, data providers) you need to restart the SKserver.  If you have logged into Security you get that click-on option in the server page, however this does NOT restart the server all it seems to do is to shut it down.  After using it I get the message "not connected to server" and reloading the web page does not help.  I have to go back to the OpenPlotter page to restart the SKserver.

**Comment by tkurki** [comment]
How does OpenPlotter run sk server? Restart server functionality relies on something like systemd to start the server.

Restarting automatically would be a good guard against the server crashing

**Comment by sailoog** [comment]
You are trying to update signal k server on openplotter 0.17.1. As I have said before we will not update the current signal k server version on 0.17.1 because that involves changes on openplotter code. You will see that kind of error.

On openplotter 1.x.x (based on raspbian stretch) we are no longer installing signal k server from github, we will install and update from npm and openplotter code will be adapted to that change.

**Comment by CaptainRon47** [comment]
So bad memory on my part.  the restart in the stand alone SignalK server also only shuts the server down, I have to restart it from the terminal (where I started it to begin with).

**Comment by FredericGuilbault** [comment]
Where is the build script you use to package all the stuff on the raspbian to make it openplotter flavour ?

**Comment by sailoog** [comment]
It is not just one. We will publish them when they are ready if you need

**Comment by FredericGuilbault** [comment]
Not that I need them but I would probably contribute. 
Updating SKserver is also a need for me and I don't want to just do it on the fly and make my install unique.

**Comment by e-sailing** [comment]
Take a raspbian image git clone openplotter in .config -> use the bash scripts in the update folder. There will be some errors solve them. Install SignalK as it is done in the script (for master). Install SignalK as it discribed on SignalK side (using V1.0.0 wifi).

**Comment by FredericGuilbault** [comment]
As I read, there will be no signalk upgrade support for the 1.7.x ? 
So this issue is convicted to be closed with a "won't fix" ?
