### ISSUE TITLE
hardcoded terminal 

### ISSUE THREAD

**Issue by FredericGuilbault** [sailoog/openplotter#240]
Me agan ... 

I came across this error. The problem is Im using `terminator` not `lxterminal`. 

```
Traceback (most recent call last):
  File "/home/pi/.config/openplotter/openplotter", line 466, in default_desktop
    subprocess.Popen(['lxterminal', '-e', 'bash', self.currentpath+'/update/default_openplotter_desk.sh'])
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

It would be better to use `x-terminal-emulator` This would let xdg select the preffered terminal of the user.

**Comment by sailoog** [comment]
I will try this, thanks.
