### ISSUE TITLE
In v2.x.x,  openplotter crash when ~/.signalk is missing 

### ISSUE THREAD

**Issue by FredericGuilbault** [sailoog/openplotter#250]
On my install, signalk run under it's own user.  So I don't have any `~/.signalK` for the user of openplotter. This make openplotter crash like this: 
```
Traceback (most recent call last):
  File "./openplotter", line 4157, in <module>
    MainFrame().Show()
  File "./openplotter", line 50, in __init__
    self.SK_settings = SK_settings()
  File "/var/www/openplotter/classes/SK_settings.py", line 28, in __init__
    self.load()
  File "/var/www/openplotter/classes/SK_settings.py", line 102, in load
    if not OPcan: self.data['pipedProviders'].append({'pipeElements': [{'type': 'providers/simple', 'options': {'logging': False, 'type': 'NMEA2000', 'subOptions': {'device': '/dev/ttyOP_', 'type': 'ngt-1'}}}], 'enabled': False, 'id': 'OPcan'})
KeyError: 'pipedProviders'
```

1) it should not make openplotter crash, 
2) The Folder location variable should be be the same for all the services that Openplotter manage in his config.(`self.home+'/.signalk/settings.json'`) 

---
This is what im gonna work on in the next days.

**Comment by FredericGuilbault** [comment]
My work branch is here: 
https://github.com/FredericGuilbault/openplotter/tree/bug/handle_missing_signalkConfFile

I will make a pull request when Im done

**Comment by FredericGuilbault** [comment]
@sailoog  in`classes/conf.py` Should I use `Conf` or `Conf2` ?
